#!/usr/bin/env php
<?php

set_time_limit(0);

$app = require_once __DIR__ . "/app.php";

/** @var \Knp\Console\Application $console */
$console = $app["console"];
$console->add(new \Hierall\Command\FillCatalogues());
$console->run();